# Generated by Django 4.1.7 on 2023-03-14 15:11

from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.admin import User
import django.db.models.deletion


class Migration(migrations.Migration):
    
    user = User.objects.get(username='admin')

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SocialTravel', '0002_post_un_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(default=user.id, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
