# Generated by Django 4.1.7 on 2023-03-22 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialTravel', '0006_alter_profile_user_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 22, 0, 11, 22, 485195)),
            preserve_default=False,
        ),
    ]
